default: &default
  adapter: mysql2
  encoding: utf8
  database: seamless
  username: root
  pool: 5
  timeout: 5000

production:
  <<: *default
  password: lasagnawithbechamelsauce2014
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  password: root
  socket: /Applications/MAMP/tmp/mysql/mysql.sock