default: &default
  adapter: mysql2
  encoding: utf8
  database: seamless
  username: root
  pool: 5
  timeout: 5000

development:
  <<: *default
  password: root
  socket: /Applications/MAMP/tmp/mysql/mysql.sock

# production:
#   <<: *default
#   password: lasagnawithbechamelsauce2014


production:
  adapter: mysql2
  host: us-cdbr-iron-east-04.cleardb.net
  encoding: utf8
  database: heroku_3b9257af6e8ee63
  username: bddb17fac2d557
  password: af4c8d51
  pool: 5
  timeout: 5000
