default: &default
  adapter: mysql2
  encoding: utf8
  database: seamless
  username: root
  pool: 5
  timeout: 5000

development:
  <<: *default
  password: lasagnawithbechamelsauce2014
  #password: root
  #socket: /Applications/MAMP/tmp/mysql/mysql.sock